CREATE TABLE IF NOT EXISTS Recipe(
	id INT PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	description VARCHAR(500) NOT NULL
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Steps(
	id INT NOT NULL,
	order INT NOT NULL,
	step VARCHAR(500) NOT NULL,
	PRIMARY KEY(id, order),
	FOREIGN KEY (id) REFERENCES Recipe(id)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Food(
	id INT PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	fat DECIMAL NOT NULL,
	sugar DECIMAL NOT NULL,
	kcal DECIMAL NOT NULL
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Categories(
	id INT NOT NULL,
	order INT NOT NULL,
	Category VARCHAR(500) NOT NULL,
	PRIMARY KEY(id, order),
	FOREIGN KEY (id) REFERENCES Food(id)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Tool(
	id INT PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	instruction_for_use VARCHAR(500) NOT NULL
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS QuantityOfFood(
	id INT NOT NULL,
	quantity INT NOT NULL,
	PRIMARY KEY(id, quantity),
	FOREIGN KEY (id) REFERENCES Food(id)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Requires(
	id_r INT NOT NULL,
	id_f INT NOT NULL,
	quantity INT NOT NULL,
	id_t INT NOT NULL,
	PRIMARY KEY(id_r, id_f, quantity),
	FOREIGN KEY (id_r) REFERENCES Recipe(id)
	FOREIGN KEY (id_f) REFERENCES Food(id)
	FOREIGN KEY (quantity) REFERENCES QuantityOfFood(quantity)
)ENGINE=InnoDB;